const roomNotice = "To be announced. Room assignments are tentative and will be based on registration.";

export const events = {
    "intro-to-javascript": {
        title: "Intro to JavaScript",
        time: "Saturday, October 10 · 12:00-2:00 PM",
        duration: "~2 hours",
        room: roomNotice,
        description: "An introductory experience that explores topics like syntax, DOM manipulation, fetching APIs, and working with JSON.",
    },
    "intro-to-python": {
        title: "Intro to Python",
        time: "Saturday, October 10 · 12:00-1:00 PM",
        duration: "~1 hour",
        room: roomNotice,
        description: "An introductory experience covering Python fundamentals such as syntax, variables, data types, control flow, and functions.",
    },
    "data-analytics-with-python": {
        title: "Data Analytics with Python",
        time: "Saturday, October 10 · 1:00-3:00 PM",
        duration: "~2 hours",
        room: roomNotice,
        description: "Build a command-line Python application that helps people explore a public dataset related to aviation, weather, space, or another Into the Skies theme. Your project should make it easy to navigate, search, filter, compare, or visualize the data in a meaningful way. You may build a graphical interface, but judging will focus on the quality of the data presentation, usability, and functionality.",
    },
    "intro-to-neural-networks": {
        title: "Intro to Neural Networks",
        time: "Saturday, October 10 · 3:00-5:00 PM",
        duration: "~2 hours",
        room: roomNotice,
        description: "An introductory experience exploring how neural networks are structured and how they learn, covering topics like layers, activation functions, and basic training concepts.",
    },
    "intro-to-web-design": {
        title: "Intro to Web Design",
        time: "Saturday, October 10 · 4:00-5:00 PM",
        duration: "~1 hour",
        room: roomNotice,
        description: "An introductory experience covering the fundamentals of building websites, including layout, styling, and design principles for creating an effective web page.",
    },
    "intro-to-3d-design-and-cad": {
        title: "Intro to 3D Design and CAD",
        time: "Saturday, October 10 · 4:00-5:30 PM",
        duration: "~1.5 hours",
        room: roomNotice,
        description: "An introductory experience covering the basics of 3D modeling and computer-aided design, including core tools and design principles for building 3D models.",
    },
    "web-design-for-awareness": {
        title: "Web Design for Awareness",
        time: "Saturday, October 10 · 5:00-6:30 PM",
        duration: "~1.5 hours",
        room: roomNotice,
        description: "You are the founder of a nonprofit working to raise awareness about an issue related to the skies, the atmosphere, or space. Design and build an effective website that educates visitors, communicates your mission, and inspires action for your chosen cause.",
    },
    "environmental-ai-ml": {
        title: "Implementing AI/ML for Environmental Action",
        time: "Saturday, October 10 · 5:00-8:00 PM",
        duration: "~3 hours",
        room: roomNotice,
        description: "Build an AI or machine learning solution that promotes environmental sustainability. Your project can use prediction, automation, computer vision, natural language processing, or data analysis to address a meaningful environmental problem and contribute to a cleaner, healthier, or more sustainable future.",
    },
    "prompt-engineering": {
        title: "Prompt Engineering",
        time: "Saturday, October 10 · 6:30-7:00 PM",
        duration: "~30 minutes",
        room: roomNotice,
        description: "An introductory experience on how to craft effective prompts for AI image generation tools, covering techniques for guiding AI models toward creative and intentional results.",
    },
    "ai-generated-art-contest": {
        title: "AI-Generated Art Contest",
        time: "Saturday, October 10 · 7:00-8:00 PM",
        duration: "~1 hour",
        room: roomNotice,
        description: "Design a unique AI-generated image centered around the theme Into the Skies. You may use any AI image generation platform to create a visually striking work that showcases creativity, originality, and artistic storytelling. This event is just for fun, so points awarded for it are halved.",
    },
    "intro-to-ai-ethics": {
        title: "Intro to AI Ethics",
        time: "Saturday, October 10 · 8:00-9:00 PM",
        duration: "~1 hour",
        room: roomNotice,
        description: "An introductory experience exploring key ethical considerations in artificial intelligence, including bias, accountability, and societal impact.",
    },
    "intro-to-java": {
        title: "Intro to Java",
        time: "Saturday, October 10 · 9:00-10:00 PM",
        duration: "~1 hour",
        room: roomNotice,
        description: "An introductory experience covering Java fundamentals such as syntax, object-oriented basics, and simple program structure.",
    },
    "ai-ethics-panel": {
        title: "AI Ethics Panel Discussion",
        time: "Saturday, October 10 · Preparation 9:00-10:00 PM · Panel 10:00-11:00 PM",
        duration: "~2 hours",
        room: roomNotice,
        description: "Listen to our panelists debate a contemporary issue in artificial intelligence. Panelists will have one hour to research the issue and prepare their perspective before a moderator guides an open discussion. The audience will evaluate the reasoning, evidence, communication, and collaboration on display before helping choose the winners through a vote.",
    },
    karaoke: {
        title: "Karaoke",
        time: "Saturday, October 10 · 11:00 PM-12:00 AM",
        duration: "~1 hour",
        room: roomNotice,
        description: "Take a quick break from the madness and come sing. Pick a favorite song, or simply join in and sing along.",
    },
    "tbd-workshop": {
        title: "TBD Workshop",
        time: "Saturday, October 10 · 11:00 PM-12:00 AM",
        duration: "~1 hour",
        room: roomNotice,
        description: "More details about this workshop are coming soon.",
    },
    "tbd-fun-activity": {
        title: "TBD Fun Activity",
        time: "Saturday, October 10 · 11:00 PM-12:00 AM",
        duration: "~1 hour",
        room: roomNotice,
        description: "More details about this activity are coming soon.",
    },
    "midnight-snack": {
        title: "Midnight Snack",
        time: "Sunday, October 11 · 12:00-1:00 AM",
        duration: "~1 hour",
        room: roomNotice,
        description: "Join us for a short snack to stay fueled for the night's coding activities.",
    },
    "chess-tournament": {
        title: "Chess Tournament",
        time: "Sunday, October 11 · 12:00-2:00 AM",
        duration: "~2 hours",
        room: roomNotice,
        description: "Whether you are a beginner or grandmaster, enter the chess tournament for a chance to win a prize or simply have a good time.",
    },
    "movie-night": {
        title: "Movie Night",
        time: "Sunday, October 11 · 1:00-3:00 AM",
        duration: "~2 hours",
        room: roomNotice,
        description: "Join us for a fun and relaxing movie viewing. The movie selection is coming soon.",
    },
    "intro-to-vibe-coding": {
        title: "Intro to Vibe Coding",
        time: "Sunday, October 11 · 3:00-4:00 AM",
        duration: "~1 hour",
        room: roomNotice,
        description: "An introductory experience covering how to build software by communicating with AI coding tools through prompts and iteration. Topics include human-in-the-loop workflows, context engineering, and more.",
    },
    "vibe-coded-space-game": {
        title: "Vibe-Coded Video Game Contest",
        time: "Sunday, October 11 · 4:00-6:00 AM",
        duration: "~2 hours",
        room: roomNotice,
        description: "Build a functional, playable space-themed game entirely through vibe coding and AI-assisted programming tools. You may only copy and paste code generated by AI, and may not manually edit or debug the code yourself. Guide the project through prompts and iteration to see how far you can take your idea. Points awarded for this event are halved.",
    },
    "intro-to-html-css-react": {
        title: "Intro to HTML and CSS + React",
        time: "Sunday, October 11 · 6:00-7:00 AM",
        duration: "~1 hour",
        room: roomNotice,
        description: "An introductory experience covering the fundamentals of building web pages, including HTML structure and CSS styling.",
    },
    "intro-to-advanced-algorithms": {
        title: "Intro to Advanced Algorithms",
        time: "Sunday, October 11 · 7:00-8:00 AM",
        duration: "~1 hour",
        room: roomNotice,
        description: "An introductory experience covering algorithmic analysis and problem-solving techniques used in competitive programming.",
    },
    "programming-tournament": {
        title: "Programming Tournament",
        time: "Sunday, October 11 · 8:00-10:00 AM",
        duration: "~2 hours",
        room: roomNotice,
        description: "Put your competitive programming skills to the test. The full challenge prompt is coming soon.",
    },
    "intro-to-swift-and-swiftui": {
        title: "Intro to Swift and SwiftUI",
        time: "Sunday, October 11 · 8:00-10:00 AM",
        duration: "~2 hours",
        room: roomNotice,
        description: "Beginners will cover Swift fundamentals such as syntax, variables, and basic control flow. Hackers with programming experience can continue into SwiftUI and learn how to build user interfaces for iOS apps.",
    },
};

export const scheduleEventSlugs = {
    "intro to javascript": "intro-to-javascript",
    "intro to python": "intro-to-python",
    "data analytics with python": "data-analytics-with-python",
    "intro to neural networks": "intro-to-neural-networks",
    "intro to web design": "intro-to-web-design",
    "intro to 3d design and cad": "intro-to-3d-design-and-cad",
    "web design for awareness": "web-design-for-awareness",
    "implementing ai/ml for environmental action": "environmental-ai-ml",
    "prompt engineering": "prompt-engineering",
    "ai-generated art contest": "ai-generated-art-contest",
    "intro to ai ethics": "intro-to-ai-ethics",
    "intro to java": "intro-to-java",
    "preparation for ai ethics mock panel": "ai-ethics-panel",
    "panel discussion and voting for the winner!": "ai-ethics-panel",
    karaoke: "karaoke",
    "midnight snack": "midnight-snack",
    "chess tournament": "chess-tournament",
    "movie night": "movie-night",
    "intro to vibe coding": "intro-to-vibe-coding",
    "vibe-coded video game contest": "vibe-coded-space-game",
    "intro to html and css + react": "intro-to-html-css-react",
    "intro to advanced algorithms": "intro-to-advanced-algorithms",
    "programming tournament": "programming-tournament",
    "intro to swift (beginner) and intro to swiftui (advanced)": "intro-to-swift-and-swiftui",
};
