const roomNotice = "Room to be announced.";

export const events = {
    "intro-to-javascript": {
        title: "Intro to JavaScript + React.js",
        time: "Saturday, October 10 · 12:00-2:00 PM",
        duration: "~2 hours",
        room: "Room 154",
        description: "Explore JavaScript syntax, DOM manipulation, fetching APIs, and working with JSON, then learn the basics of building interfaces with React.js.",
    },
    "intro-to-python": {
        title: "Intro to Python",
        time: "Saturday, October 10 · 12:00-1:00 PM",
        duration: "~1 hour",
        room: "Room 153",
        description: "An introductory experience covering Python fundamentals such as syntax, variables, data types, control flow, and functions.",
    },
    "data-analytics-with-python": {
        title: "Data Analytics with Python",
        time: "Saturday, October 10 · 1:00-3:00 PM",
        duration: "~2 hours",
        room: "Room 153",
        description: "Build a command-line Python application that helps people explore a public dataset related to aviation, weather, space, or another Into the Skies theme. Your project should make it easy to navigate, search, filter, compare, or visualize the data in a meaningful way. You may build a graphical interface, but judging will focus on the quality of the data presentation, usability, and functionality.",
    },
    "intro-to-neural-networks": {
        title: "Intro to Neural Networks",
        time: "Saturday, October 10 · 3:00-5:00 PM",
        duration: "~2 hours",
        room: "Room 152",
        description: "An introductory experience exploring how neural networks are structured and how they learn, covering topics like layers, activation functions, and basic training concepts.",
    },
    "intro-to-web-design": {
        title: "Intro to Web Design",
        time: "Saturday, October 10 · 4:00-5:00 PM",
        duration: "~1 hour",
        room: "Room 153",
        description: "An introductory experience covering the fundamentals of building websites, including layout, styling, and design principles for creating an effective web page.",
    },
    "intro-to-circuitry": {
        title: "Intro to Circuitry",
        time: "Saturday, October 10 · 4:00-5:30 PM",
        duration: "~1.5 hours",
        room: "Room 154",
        description: "Nicholas Kopaliani studies physics at Princeton University and spent much of high school exploring circuitry. He will lead an introductory workshop, sharing his experience and helping participants get started with circuits.",
    },
    "web-design-for-awareness": {
        title: "Web Design for Awareness",
        time: "Saturday, October 10 · 5:00-6:30 PM",
        duration: "~1.5 hours",
        room: "Room 153",
        description: "You are the founder of a nonprofit working to raise awareness about an issue related to the skies, the atmosphere, or space. Design and build an effective website that educates visitors, communicates your mission, and inspires action for your chosen cause.",
    },
    "environmental-ai-ml": {
        title: "Implementing AI/ML for Environmental Action",
        time: "Saturday, October 10 · 5:00-8:00 PM",
        duration: "~3 hours",
        room: "Room 154",
        description: "Build an AI or machine learning solution that promotes environmental sustainability. Your project can use prediction, automation, computer vision, natural language processing, or data analysis to address a meaningful environmental problem and contribute to a cleaner, healthier, or more sustainable future.",
    },
    "intro-to-generative-ai": {
        title: "Intro to Generative AI",
        time: "Saturday, October 10 · 6:30-8:00 PM",
        duration: "~1.5 hours",
        room: "Room 153",
        description: "Join guest workshop leader Aryahi Pimple for an introduction to generative AI.",
    },
    "estimathon": {
        title: "Estimathon",
        time: "Saturday, October 10 · 7:00-8:00 PM",
        duration: "~1 hour",
        room: "Room 152",
        description: "Join a team estimation challenge and put your problem-solving skills to the test.",
    },
    "intro-to-ai-ethics": {
        title: "Intro to AI Ethics",
        time: "Saturday, October 10 · 8:00-9:00 PM",
        duration: "~1 hour",
        room: "Room 153",
        description: "An introductory experience exploring key ethical considerations in artificial intelligence, including bias, accountability, and societal impact.",
    },
    "intro-to-java": {
        title: "Intro to Java",
        time: "Saturday, October 10 · 9:00-10:00 PM",
        duration: "~1 hour",
        room: "Room 154",
        description: "An introductory experience covering Java fundamentals such as syntax, object-oriented basics, and simple program structure.",
    },
    "ai-ethics-panel": {
        title: "AI Panel Discussion",
        time: "Saturday, October 10 · Preparation 9:00-10:00 PM · Panel 10:00-11:00 PM",
        duration: "~2 hours",
        room: "Preparation: Room 153; discussion: New Gym",
        description: "Listen to our panelists debate a contemporary issue in artificial intelligence. Panelists will have one hour to research the issue and prepare their perspective before a moderator guides an open discussion. The audience will evaluate the reasoning, evidence, communication, and collaboration on display before helping choose the winners through a vote.",
    },
    karaoke: {
        title: "Karaoke",
        time: "Saturday, October 10 · 11:00 PM-12:00 AM",
        duration: "~1 hour",
        room: "Room 152",
        description: "Take a quick break from the madness and come sing. Pick a favorite song, or simply join in and sing along.",
    },
    "tbd-workshop": {
        title: "TBD Workshop",
        time: "Saturday, October 10 · 11:00 PM-12:00 AM",
        duration: "~1 hour",
        room: roomNotice,
        description: "More details about this workshop are coming soon.",
    },
    "tbd-fun-activity": {
        title: "TBD Fun Activity",
        time: "Saturday, October 10 · 11:00 PM-12:00 AM",
        duration: "~1 hour",
        room: roomNotice,
        description: "More details about this activity are coming soon.",
    },
    "midnight-snack": {
        title: "Midnight Snack",
        time: "Sunday, October 11 · 12:30-7:00 AM",
        duration: "Available overnight",
        room: "Cafeteria",
        description: "Snacks will be available overnight to keep you fueled while you build.",
    },
    "chess-tournament": {
        title: "Chess Tournament",
        time: "Saturday, October 10 · 11:00 PM-12:00 AM",
        duration: "~1 hour",
        room: "Room 153",
        description: "Whether you are a beginner or grandmaster, enter the chess tournament for a chance to win a prize or simply have a good time.",
    },
    "movie-night": {
        title: "Movie Night",
        time: "Sunday, October 11 · 1:00-3:00 AM",
        duration: "~2 hours",
        room: "Room 152",
        description: "Join us for a fun and relaxing movie viewing. The movie selection is coming soon.",
    },
    "intro-to-vibe-coding": {
        title: "Intro to Vibe Coding",
        time: "Sunday, October 11 · 3:00-4:00 AM",
        duration: "~1 hour",
        room: "Room 154",
        description: "An introductory experience covering how to build software by communicating with AI coding tools through prompts and iteration. Topics include human-in-the-loop workflows, context engineering, and more.",
    },
    "vibe-coded-space-game": {
        title: "Vibe-Coded Video Game Contest",
        time: "Sunday, October 11 · 4:00-6:00 AM",
        duration: "~2 hours",
        room: "Room 154",
        description: "Build a functional, playable space-themed game entirely through vibe coding and AI-assisted programming tools. You may only copy and paste code generated by AI, and may not manually edit or debug the code yourself. Guide the project through prompts and iteration to see how far you can take your idea. Points awarded for this event are halved.",
    },
    "intro-to-html-css-react": {
        title: "Intro to HTML and CSS",
        time: "Sunday, October 11 · 6:00-7:00 AM",
        duration: "~1 hour",
        room: "Room 153",
        description: "An introductory experience covering the fundamentals of building web pages, including HTML structure and CSS styling.",
    },
    "intro-to-advanced-algorithms": {
        title: "Intro to Advanced Algorithms",
        time: "Sunday, October 11 · 7:00-8:00 AM",
        duration: "~1 hour",
        room: "Room 154",
        description: "An introductory experience covering algorithmic analysis and problem-solving techniques used in competitive programming.",
    },
    "intro-to-swift-and-swiftui": {
        title: "Intro to Swift",
        time: "Sunday, October 11 · 8:00-10:00 AM",
        duration: "~2 hours",
        room: "Room 154",
        description: "An introductory experience covering Swift fundamentals such as syntax, variables, and basic control flow.",
    },
    "nathaniel-daw": {
        title: "Guest Talk: Nathaniel Daw",
        time: "Saturday, October 10 · 1:00-2:00 PM",
        duration: "~1 hour",
        room: "Room 152",
        // Research bio: https://pni.princeton.edu/people/nathaniel-daw
        description: "Nathaniel Daw is a computational neuroscience professor at Princeton University. His research combines neuroscience, psychology, and machine learning to understand how people learn from experience, make decisions, and respond to rewards.",
    },
    "yushu-cheng": {
        title: "Guest Talk: Yushu A. Cheng",
        time: "Saturday, October 10 · 5:30-6:30 PM",
        duration: "~1 hour",
        room: "Room 152",
        // Research bio: https://orcid.org/0009-0006-9816-9139
        description: "Yushu A. Cheng is a postdoctoral researcher in environmental engineering at Princeton University. Her research uses machine learning and large language models to study how contaminants break down in the environment.",
    },
    "vritika-singh": {
        title: "Women in STEM and Undergraduate CS Life",
        time: "Saturday, October 10 · 6:30-7:00 PM",
        duration: "~30 minutes",
        room: "Room 152",
        description: "Vritika Singh studies Computer Science and Artificial Intelligence, with pre-business studies, at UNC Chapel Hill. She will speak about women in STEM and undergraduate computer science life and academics.",
    },
};

export const scheduleEventSlugs = {
    "intro to javascript + react.js": "intro-to-javascript",
    "intro to python": "intro-to-python",
    "data analytics with python": "data-analytics-with-python",
    "intro to neural networks": "intro-to-neural-networks",
    "intro to web design": "intro-to-web-design",
    "intro to circuitry": "intro-to-circuitry",
    "web design for awareness": "web-design-for-awareness",
    "implementing ai/ml for environmental action": "environmental-ai-ml",
    "intro to generative ai": "intro-to-generative-ai",
    "intro to ai ethics": "intro-to-ai-ethics",
    "intro to java": "intro-to-java",
    "preparation for ai ethics mock panel": "ai-ethics-panel",
    "ai panel discussion": "ai-ethics-panel",
    estimathon: "estimathon",
    karaoke: "karaoke",
    "midnight snack": "midnight-snack",
    "chess tournament": "chess-tournament",
    "movie night": "movie-night",
    "intro to vibe coding": "intro-to-vibe-coding",
    "vibe-coded video game contest": "vibe-coded-space-game",
    "intro to html and css": "intro-to-html-css-react",
    "intro to advanced algorithms": "intro-to-advanced-algorithms",
    "intro to swift": "intro-to-swift-and-swiftui",
};

// Room assignments from the organizers' logistics schedule.
export const scheduleRooms = {
    "check-in begins": "New Gym",
    "opening ceremony": "New Gym",
    hacking: "Cafeteria",
    "team building": "Room 155",
    lunch: "Cafeteria",
    dinner: "Cafeteria",
    "preparation for ai ethics mock panel": "Room 153",
    "ai panel discussion": "New Gym",
    sleep: "Boys: Rooms 161, 163, 165, 143\nGirls: Rooms 142, 144, 146",
    breakfast: "Cafeteria",
    "projects due and judging begins": "Room 155",
    "closing ceremony": "New Gym",
};
